export const SEED_VOCABULARY = [
  // Greetings (10)
  { turkish: 'Merhaba', english: 'Hello', category: 'greetings' },
  { turkish: 'Günaydın', english: 'Good morning', category: 'greetings' },
  { turkish: 'İyi akşamlar', english: 'Good evening', category: 'greetings' },
  { turkish: 'Nasılsın?', english: 'How are you?', category: 'greetings' },
  { turkish: 'Teşekkür ederim', english: 'Thank you', category: 'greetings' },
  { turkish: 'Lütfen', english: 'Please', category: 'greetings' },
  { turkish: 'Evet', english: 'Yes', category: 'greetings' },
  { turkish: 'Hayır', english: 'No', category: 'greetings' },
  { turkish: 'Tamam', english: 'Okay', category: 'greetings' },
  { turkish: 'Görüşürüz', english: 'See you later', category: 'greetings' },
  // Food (12)
  { turkish: 'Kahve', english: 'Coffee', category: 'food' },
  { turkish: 'Ekmek', english: 'Bread', category: 'food' },
  { turkish: 'Peynir', english: 'Cheese', category: 'food' },
  { turkish: 'Et', english: 'Meat', category: 'food' },
  { turkish: 'Tavuk', english: 'Chicken', category: 'food' },
  { turkish: 'Balık', english: 'Fish', category: 'food' },
  { turkish: 'Salata', english: 'Salad', category: 'food' },
  { turkish: 'Pilav', english: 'Rice', category: 'food' },
  { turkish: 'Meze', english: 'Appetizers', category: 'food' },
  { turkish: 'Çorba', english: 'Soup', category: 'food' },
  { turkish: 'Kebap', english: 'Kebab', category: 'food' },
  { turkish: 'Baklava', english: 'Baklava', category: 'food' },
  // Drinks (8)
  { turkish: 'Çay', english: 'Tea', category: 'drinks' },
  { turkish: 'Su', english: 'Water', category: 'drinks' },
  { turkish: 'Bira', english: 'Beer', category: 'drinks' },
  { turkish: 'Şarap', english: 'Wine', category: 'drinks' },
  { turkish: 'Türk kahvesi', english: 'Turkish coffee', category: 'drinks' },
  { turkish: 'Ayran', english: 'Yogurt drink', category: 'drinks' },
  { turkish: 'Portakal suyu', english: 'Orange juice', category: 'drinks' },
  { turkish: 'Börek', english: 'Pastry', category: 'food' },
  // Numbers (10)
  { turkish: 'Bir', english: 'One', category: 'numbers' },
  { turkish: 'İki', english: 'Two', category: 'numbers' },
  { turkish: 'Üç', english: 'Three', category: 'numbers' },
  { turkish: 'Dört', english: 'Four', category: 'numbers' },
  { turkish: 'Beş', english: 'Five', category: 'numbers' },
  { turkish: 'On', english: 'Ten', category: 'numbers' },
  { turkish: 'Yirmi', english: 'Twenty', category: 'numbers' },
  { turkish: 'Elli', english: 'Fifty', category: 'numbers' },
  { turkish: 'Yüz', english: 'Hundred', category: 'numbers' },
  { turkish: 'Kaç?', english: 'How many?', category: 'numbers' },
  // Key phrases (10)
  { turkish: 'Hesap lütfen', english: 'Check please', category: 'phrases' },
  { turkish: 'Ne kadar?', english: 'How much?', category: 'phrases' },
  { turkish: 'Anlamadım', english: "I don't understand", category: 'phrases' },
  {
    turkish: 'Tekrar eder misiniz?',
    english: 'Can you repeat?',
    category: 'phrases',
  },
  { turkish: 'İstiyorum', english: 'I want', category: 'phrases' },
  {
    turkish: 'İstemiyorum',
    english: "I don't want",
    category: 'phrases',
  },
  { turkish: 'Nerede?', english: 'Where?', category: 'phrases' },
  { turkish: 'Çok güzel', english: 'Very beautiful', category: 'phrases' },
  { turkish: 'Aferin', english: 'Well done', category: 'phrases' },
  { turkish: 'Hoş geldiniz', english: 'Welcome', category: 'phrases' },
];
